title: Observatório Cidadão das Mídias
logo: /assets/img/LOGO.png
description: Investigamos o tratamento midiático brasileiro da realidade.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
