title: /assets/img/LOGO.png
logo: /assets/img/LOGO.png
description: Investigamos o tratamento midiático brasileiro da realidade.
show_downloads: false
google_analytics: G-3S491F0ZNG
theme: jekyll-theme-minimal
