title: OBSERVATÓRIO CIDADÃO DAS MÍDIAS
logo: /assets/img/LOGO.png
description: Investigamos o tratamento midiático brasileiro dado à realidade.
show_downloads: false
google_analytics: G-3S491F0ZNG
theme: jekyll-theme-minimal
